<?php

return array(
    //'配置项'=>'配置值'
    'resource_path' => '/Public/Admin/',
    'CONTROLLER_LEVEL' => 1, //多级控制器是指控制器可以通过子目录把某个控制器层分组存放，首先需要设置控制器的分级层次
    //给配置菜单命名
    'Orders'=>'订单',
    'Orders_buy_orders'=>'购买订单列表',
    'Orders_rent_orders'=>'租赁订单列表',
    'Orders_diy_orders'=>'定制订单列表',
    'Members'=>'会员',
    'Members_lists'=>'会员列表',
    'Members_collection'=>'会员收藏列表',
    'Members_focus'=>'会员关注列表',
    'News'=>'内容',
    'News_startup_lists'=>'APP启动图列表',
    'News_banner_lists'=>'banner列表',
    'News_lists'=>'新闻资讯列表',
    'Works'=>'作品',
    'Works_lists'=>'作品列表',
    'Works_cat_lists'=>'艺术画分类列表',
    'Works_topic_lists'=>'艺术画主题列表',
    'Works_work_with_showtype'=>'装饰风格',
    'Artists'=>'艺术家',
    'Artists_lists'=>'艺术家列表',
    'Galleries'=>'线下画廊',
    'Galleries_lists'=>'线下画廊列表',
    'Credit'=>'积分',
    'Credit_lists'=>'积分列表',
    'Credit_setting'=>'积分配置',
    'Coupons'=>'卡券',
    'Coupons_lists'=>'卡券列表',
    'Setting'=>'设置',
    'Setting_mobile_index_config'=>'微商城首页配置',
    'Setting_dashboard'=>'后台首页统计',
    'Setting_sms_config'=>'短信配置',
    'Setting_payment_config_wx'=>'微信支付配置',
    'Setting_payment_config_alipay'=>'支付宝配置',
    'Setting_mobile_index_showtype_config'=>'装饰风格',
);
